### ISSUE TITLE
ledger table enhancement

### ISSUE THREAD

**Issue by jbfoushee** [microsoft/sqlworkshops-sql2022workshop#84]
Exercise 1: Using an updatable ledger table
Add a step 8.5 : Run the verifyledger.sql to see that the ledger is consistent to this point.
Step 12: Because the ledger hasn't been checkpointed, the same last_verified_block_id is reflected.
Add a new step 13: (same as step 7) Let's generate a new digest by executing the script generatedigest.sql. Save the output value (including the braces) to be used for verifying the ledger.. You will use this in a later step. This provides me a snapshot of the data at a point in time.
Add a new step 14: Run the verifyledger.sql to see that the ledger now reflects the new last_verified_block_id.
Add a new step 15: Remove any character from the hash in verifyledger.sql and re-run the code. Notice the proc states the hash does not match, suggesting tampering.

Exercise 2: Using an append-only ledger table
Script within appchangemaryssalary.sql should be enclosed in a transaction, in case user forgot to create audit table.

Exercise 3: Protecting Ledger tables from DDL changes
Saw a misspelled "syadmin"

**Comment by rgward** [comment]
Great suggestions. Here is what I've done.

1. Updated Exercise 1 to include two digest generates and verifications. I did not include tampering with the digest because the true scenario to "tamper" is tampering with the ledger itself
2. Changed the appchangemarysalary.sql to use a transaction.
3. Fixed the typo
